ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usuarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "choferes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "camiones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "viajes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "paradas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reportes_chofer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gastos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mantenimientos_vehiculos" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "deny_all_prisma_migrations" ON "_prisma_migrations";
DROP POLICY IF EXISTS "usuarios_select_authenticated" ON "usuarios";
DROP POLICY IF EXISTS "usuarios_insert_authenticated" ON "usuarios";
DROP POLICY IF EXISTS "usuarios_update_own" ON "usuarios";
DROP POLICY IF EXISTS "usuarios_delete_authenticated" ON "usuarios";
DROP POLICY IF EXISTS "choferes_select_authenticated" ON "choferes";
DROP POLICY IF EXISTS "choferes_insert_authenticated" ON "choferes";
DROP POLICY IF EXISTS "choferes_update_authenticated" ON "choferes";
DROP POLICY IF EXISTS "choferes_delete_authenticated" ON "choferes";
DROP POLICY IF EXISTS "camiones_select_authenticated" ON "camiones";
DROP POLICY IF EXISTS "camiones_insert_authenticated" ON "camiones";
DROP POLICY IF EXISTS "camiones_update_authenticated" ON "camiones";
DROP POLICY IF EXISTS "camiones_delete_authenticated" ON "camiones";
DROP POLICY IF EXISTS "viajes_select_authenticated" ON "viajes";
DROP POLICY IF EXISTS "viajes_insert_authenticated" ON "viajes";
DROP POLICY IF EXISTS "viajes_update_authenticated" ON "viajes";
DROP POLICY IF EXISTS "viajes_delete_authenticated" ON "viajes";
DROP POLICY IF EXISTS "paradas_select_authenticated" ON "paradas";
DROP POLICY IF EXISTS "paradas_insert_authenticated" ON "paradas";
DROP POLICY IF EXISTS "paradas_update_authenticated" ON "paradas";
DROP POLICY IF EXISTS "paradas_delete_authenticated" ON "paradas";
DROP POLICY IF EXISTS "reportes_chofer_select_authenticated" ON "reportes_chofer";
DROP POLICY IF EXISTS "reportes_chofer_insert_authenticated" ON "reportes_chofer";
DROP POLICY IF EXISTS "reportes_chofer_update_authenticated" ON "reportes_chofer";
DROP POLICY IF EXISTS "reportes_chofer_delete_authenticated" ON "reportes_chofer";
DROP POLICY IF EXISTS "gastos_select_authenticated" ON "gastos";
DROP POLICY IF EXISTS "gastos_insert_authenticated" ON "gastos";
DROP POLICY IF EXISTS "gastos_update_authenticated" ON "gastos";
DROP POLICY IF EXISTS "gastos_delete_authenticated" ON "gastos";
DROP POLICY IF EXISTS "mantenimientos_vehiculos_select_authenticated" ON "mantenimientos_vehiculos";
DROP POLICY IF EXISTS "mantenimientos_vehiculos_insert_authenticated" ON "mantenimientos_vehiculos";
DROP POLICY IF EXISTS "mantenimientos_vehiculos_update_authenticated" ON "mantenimientos_vehiculos";
DROP POLICY IF EXISTS "mantenimientos_vehiculos_delete_authenticated" ON "mantenimientos_vehiculos";

REVOKE ALL PRIVILEGES ON TABLE "_prisma_migrations" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "usuarios" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "choferes" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "camiones" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "viajes" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "paradas" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "reportes_chofer" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "gastos" FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE "mantenimientos_vehiculos" FROM PUBLIC, anon, authenticated;
