CREATE TYPE "OrigenGasto" AS ENUM ('CHOFER', 'ADMIN');

ALTER TABLE "paradas" ADD COLUMN "tramo" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "gastos" ADD COLUMN "origen" "OrigenGasto" NOT NULL DEFAULT 'ADMIN';
